/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fakhrirasyids.beataco.view.admin;

import com.fakhrirasyids.beataco.data.bot.BeatacoBot;
import com.fakhrirasyids.beataco.data.database.DBInjector;
import com.fakhrirasyids.beataco.view.admin.panels.AdminBroadcastPanel;
import com.fakhrirasyids.beataco.view.admin.panels.AdminCommandsPanel;
import com.fakhrirasyids.beataco.view.admin.panels.AdminUsersPanel;
import com.fakhrirasyids.beataco.view.login.LoginScreen;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowEvent;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.telegram.telegrambots.meta.TelegramBotsApi;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;
import org.telegram.telegrambots.updatesreceivers.DefaultBotSession;

/**
 *
 * @author Fakhri
 */
public class AdminScreen extends javax.swing.JFrame {

    private static final String IMG_PATH = "src/images/beataco_logo_circled.png";
    private Color bgColor = new Color(25, 25, 112);
    private Color btnColorFalse = new Color(25, 25, 112);
    private Color btnColorFalseClick = new Color(25, 22, 100);
    private Color btnColorFalseHover = new Color(25, 22, 135);
    private Color btnColorTrue = new Color(214, 217, 223);

    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        startBot();
        initComponents();
        initLayout();
    }

    private void initLayout() {
        this.getContentPane().setBackground(bgColor);
        Font newButtonFont = new Font(btnClose.getFont().getName(), Font.BOLD, btnClose.getFont().getSize());
        btnClose.setFont(newButtonFont);
        btnClose.setOpaque(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setBorderPainted(false);

        btnMinimize.setFont(newButtonFont);
        btnMinimize.setOpaque(false);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setBorderPainted(false);

        this.contentPanel.setLayout(new FlowLayout());
        this.contentPanel.add(new AdminCommandsPanel());
        this.contentPanel.validate();

        btnSignOut.setOpaque(false);
        btnSignOut.setContentAreaFilled(false);
        btnSignOut.setBorderPainted(false);

        btnCommands.setColor(btnColorTrue);
        btnCommands.setColorOver(btnColorTrue);
        btnCommands.setColorClick(btnColorTrue);
        btnCommands.setForeground(Color.BLACK);

        btnCommands.setEnabled(false);

        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
            }
        });

        try {
            Image img = ImageIO.read(LoginScreen.class.getClassLoader().getResourceAsStream("beataco_logo_circled.png"));
            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage(); // transform it
            Image newimg = image.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
            imageIcon = new ImageIcon(newimg);  // transform it back
            imgLogo.setIcon(imageIcon);
        } catch (IOException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void startBot() {
        try {
            TelegramBotsApi botApi = new TelegramBotsApi(DefaultBotSession.class);
            botApi.registerBot(new BeatacoBot());
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new com.fakhrirasyids.beataco.view.components.asset.RoundedButton();
        contentPanel = new javax.swing.JPanel();
        btnMinimize = new com.fakhrirasyids.beataco.view.components.asset.RoundedButton();
        btnSignOut = new com.fakhrirasyids.beataco.view.components.asset.RoundedButton();
        jLabel1 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCommands = new com.fakhrirasyids.beataco.view.components.asset.RoundedButton();
        btnUsers = new com.fakhrirasyids.beataco.view.components.asset.RoundedButton();
        btnBroadcast = new com.fakhrirasyids.beataco.view.components.asset.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.setBorderColor(new java.awt.Color(25, 25, 112));
        btnClose.setColor(new java.awt.Color(25, 25, 112));
        btnClose.setColorClick(new java.awt.Color(25, 22, 100));
        btnClose.setColorOver(new java.awt.Color(25, 22, 135));
        btnClose.setFocusPainted(false);
        btnClose.setOpaque(true);
        btnClose.setRadius(40);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setText("—");
        btnMinimize.setBorderColor(new java.awt.Color(25, 25, 112));
        btnMinimize.setColor(new java.awt.Color(25, 25, 112));
        btnMinimize.setColorClick(new java.awt.Color(25, 22, 100));
        btnMinimize.setColorOver(new java.awt.Color(25, 22, 135));
        btnMinimize.setFocusPainted(false);
        btnMinimize.setOpaque(true);
        btnMinimize.setRadius(40);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        btnSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSignOut.setText("Sign Out");
        btnSignOut.setBorderColor(new java.awt.Color(25, 25, 112));
        btnSignOut.setColor(new java.awt.Color(204, 0, 0));
        btnSignOut.setColorClick(new java.awt.Color(102, 0, 0));
        btnSignOut.setColorOver(new java.awt.Color(153, 0, 0));
        btnSignOut.setFocusPainted(false);
        btnSignOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignOut.setOpaque(true);
        btnSignOut.setRadius(40);
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administration Panel");
        jLabel1.setToolTipText("");

        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Schadow BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Beataco");

        btnCommands.setBackground(new java.awt.Color(25, 25, 112));
        btnCommands.setForeground(new java.awt.Color(255, 255, 255));
        btnCommands.setText("Commands");
        btnCommands.setBorderColor(new java.awt.Color(25, 25, 112));
        btnCommands.setColor(new java.awt.Color(25, 25, 112));
        btnCommands.setColorClick(new java.awt.Color(25, 22, 100));
        btnCommands.setColorOver(new java.awt.Color(25, 22, 135));
        btnCommands.setFocusPainted(false);
        btnCommands.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCommands.setOpaque(true);
        btnCommands.setRadius(40);
        btnCommands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommandsActionPerformed(evt);
            }
        });

        btnUsers.setBackground(new java.awt.Color(25, 25, 112));
        btnUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnUsers.setText("Users");
        btnUsers.setBorderColor(new java.awt.Color(25, 25, 112));
        btnUsers.setColor(new java.awt.Color(25, 25, 112));
        btnUsers.setColorClick(new java.awt.Color(25, 22, 100));
        btnUsers.setColorOver(new java.awt.Color(25, 22, 135));
        btnUsers.setFocusPainted(false);
        btnUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsers.setOpaque(true);
        btnUsers.setRadius(40);
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        btnBroadcast.setForeground(new java.awt.Color(255, 255, 255));
        btnBroadcast.setText("Broadcast");
        btnBroadcast.setBorderColor(new java.awt.Color(25, 25, 112));
        btnBroadcast.setColor(new java.awt.Color(25, 25, 112));
        btnBroadcast.setColorClick(new java.awt.Color(25, 22, 100));
        btnBroadcast.setColorOver(new java.awt.Color(25, 22, 135));
        btnBroadcast.setFocusPainted(false);
        btnBroadcast.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBroadcast.setOpaque(true);
        btnBroadcast.setRadius(40);
        btnBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBroadcastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSignOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
                            .addComponent(btnCommands, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBroadcast, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imgLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCommands, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBroadcast, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setState(AdminScreen.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        //        JOptionPane.showMessageDialog(null, "Administrator account not found!", "Beataco", JOptionPane.ERROR_MESSAGE);
        this.dispose();
        JFrame loginScreen = new LoginScreen();
        loginScreen.setVisible(true);
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnCommandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommandsActionPerformed
        setTabButtonListener(1);
        this.contentPanel.removeAll();
        this.contentPanel.repaint();
        this.contentPanel.setLayout(new FlowLayout());
        this.contentPanel.add(new AdminCommandsPanel());
        this.contentPanel.validate();
    }//GEN-LAST:event_btnCommandsActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        setTabButtonListener(2);
        this.contentPanel.removeAll();
        this.contentPanel.repaint();
        this.contentPanel.setLayout(new FlowLayout());
        this.contentPanel.add(new AdminUsersPanel());
        this.contentPanel.validate();
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBroadcastActionPerformed
        setTabButtonListener(3);
        this.contentPanel.removeAll();
        this.contentPanel.repaint();
        this.contentPanel.setLayout(new FlowLayout());
        this.contentPanel.add(new AdminBroadcastPanel());
        this.contentPanel.validate();
    }//GEN-LAST:event_btnBroadcastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    private void setTabButtonListener(int tabIndex) {
        if (tabIndex == 1) {
            btnCommands.setColor(btnColorTrue);
            btnCommands.setColorOver(btnColorTrue);
            btnCommands.setColorClick(btnColorTrue);
            btnCommands.setForeground(Color.BLACK);

            btnUsers.setColor(btnColorFalse);
            btnUsers.setColorOver(btnColorFalseHover);
            btnUsers.setColorClick(btnColorFalseClick);
            btnUsers.setForeground(Color.WHITE);

            btnBroadcast.setColor(btnColorFalse);
            btnBroadcast.setColorOver(btnColorFalseHover);
            btnBroadcast.setColorClick(btnColorFalseClick);
            btnBroadcast.setForeground(Color.WHITE);

            btnCommands.setEnabled(false);
            btnUsers.setEnabled(true);
            btnBroadcast.setEnabled(true);
        } else if (tabIndex == 2) {
            btnUsers.setColor(btnColorTrue);
            btnUsers.setColorOver(btnColorTrue);
            btnUsers.setColorClick(btnColorTrue);
            btnUsers.setForeground(Color.BLACK);

            btnCommands.setColor(btnColorFalse);
            btnCommands.setColorOver(btnColorFalseHover);
            btnCommands.setColorClick(btnColorFalseClick);
            btnCommands.setForeground(Color.WHITE);

            btnBroadcast.setColor(btnColorFalse);
            btnBroadcast.setColorOver(btnColorFalseHover);
            btnBroadcast.setColorClick(btnColorFalseClick);
            btnBroadcast.setForeground(Color.WHITE);

            btnCommands.setEnabled(true);
            btnUsers.setEnabled(false);
            btnBroadcast.setEnabled(true);
        } else {
            btnBroadcast.setColor(btnColorTrue);
            btnBroadcast.setColorOver(btnColorTrue);
            btnBroadcast.setColorClick(btnColorTrue);
            btnBroadcast.setForeground(Color.BLACK);

            btnCommands.setColor(btnColorFalse);
            btnCommands.setColorOver(btnColorFalseHover);
            btnCommands.setColorClick(btnColorFalseClick);
            btnCommands.setForeground(Color.WHITE);

            btnUsers.setColor(btnColorFalse);
            btnUsers.setColorOver(btnColorFalseHover);
            btnUsers.setColorClick(btnColorFalseClick);
            btnUsers.setForeground(Color.WHITE);

            btnCommands.setEnabled(true);
            btnUsers.setEnabled(true);
            btnBroadcast.setEnabled(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.fakhrirasyids.beataco.view.components.asset.RoundedButton btnBroadcast;
    private com.fakhrirasyids.beataco.view.components.asset.RoundedButton btnClose;
    private com.fakhrirasyids.beataco.view.components.asset.RoundedButton btnCommands;
    private com.fakhrirasyids.beataco.view.components.asset.RoundedButton btnMinimize;
    private com.fakhrirasyids.beataco.view.components.asset.RoundedButton btnSignOut;
    private com.fakhrirasyids.beataco.view.components.asset.RoundedButton btnUsers;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
